{{- if .Values.deploy.applicationProperties.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notejam.name" . }}
  labels:
    {{- include "notejam.labels" . | nindent 4 }}
data:
  application.properties: |-
    {{- tpl .Values.deploy.applicationProperties.properties . | nindent 4 }}
{{- end }}